BLOOD_GROUP = (
    ('a+', 'A(+ve)'),
    ('a-', 'A(-ve)'),
    ('b+', 'B(+ve)'),
    ('b-', 'B(-ve)'),
    ('ab+', 'AB(+ve)'),
    ('ab-', 'AB(-ve)'),
    ('o+', 'O(+ve)'),
    ('o-', 'O(-ve)'),
)

STATUS_CHOICE = [
    ('stu', 'Student'),
    ('job', 'Job Holder'),
    ('unemployed', 'Unemployed')
]


DISTRICT_CHOICES = [
    ('bagerhat', 'Bagerhat'),
    ('bandarban', 'Bandarban'),
    ('barguna', 'Barguna'),
    ('barisal', 'Barisal'),
    ('bhola', 'Bhola'),
    ('bogura', 'Bogura'),
    ('brahmanbaria', 'Brahmanbaria'),
    ('chandpur', 'Chandpur'),
    ('chapainawabganj', 'Chapainawabganj'),
    ('chattogram', 'Chattogram'),
    ('chuadanga', 'Chuadanga'),
    ("cox's bazar", "Cox's Bazar"),
    ('cumilla', 'Cumilla'),
    ('dhaka', 'Dhaka'),
    ('dinajpur', 'Dinajpur'),
    ('faridpur', 'Faridpur'),
    ('feni', 'Feni'),
    ('gaibandha', 'Gaibandha'),
    ('gazipur', 'Gazipur'),
    ('gopalganj', 'Gopalganj'),
    ('habiganj', 'Habiganj'),
    ('jamalpur', 'Jamalpur'),
    ('jessore', 'Jessore'),
    ('jhalokati', 'Jhalokati'),
    ('jhenaidah', 'Jhenaidah'),
    ('joypurhat', 'Joypurhat'),
    ('khagrachhari', 'Khagrachhari'),
    ('khulna', 'Khulna'),
    ('kishoreganj', 'Kishoreganj'),
    ('kurigram', 'Kurigram'),
    ('kushtia', 'Kushtia'),
    ('lakshmipur', 'Lakshmipur'),
    ('lalmonirhat', 'Lalmonirhat'),
    ('madaripur', 'Madaripur'),
    ('magura', 'Magura'),
    ('manikganj', 'Manikganj'),
    ('meherpur', 'Meherpur'),
    ('moulvibazar', 'Moulvibazar'),
    ('munshiganj', 'Munshiganj'),
    ('mymensingh', 'Mymensingh'),
    ('naogaon', 'Naogaon'),
    ('narail', 'Narail'),
    ('narayanganj', 'Narayanganj'),
    ('narsingdi', 'Narsingdi'),
    ('natore', 'Natore'),
    ('netrokona', 'Netrokona'),
    ('nilphamari', 'Nilphamari'),
    ('noakhali', 'Noakhali'),
    ('pabna', 'Pabna'),
    ('panchagarh', 'Panchagarh'),
    ('patuakhali', 'Patuakhali'),
    ('pirojpur', 'Pirojpur'),
    ('rajbari', 'Rajbari'),
    ('rajshahi', 'Rajshahi'),
    ('rangamati', 'Rangamati'),
    ('rangpur', 'Rangpur'),
    ('satkhira', 'Satkhira'),
    ('shariatpur', 'Shariatpur'),
    ('sherpur', 'Sherpur'),
    ('sirajganj', 'Sirajganj'),
    ('sunamganj', 'Sunamganj'),
    ('sylhet', 'Sylhet'),
    ('tangail', 'Tangail'),
    ('thakurgaon', 'Thakurgaon'),
]

YEARS_CHOICE = [
    ('1st', 'First Year'),
    ('2nd', 'Second Year'),
    ('3rd', 'Third Year'),
    ('4th', 'Fourth Year'),
    ('ms', 'Masters')
]