BLOOD_GROUP = (
    ('a+', 'A(+ve)'),
    ('a-', 'A(-ve)'),
    ('b+', 'B(+ve)'),
    ('b-', 'B(-ve)'),
    ('ab+', 'AB(+ve)'),
    ('ab-', 'AB(-ve)'),
    ('o+', 'O(+ve)'),
    ('o-', 'O(-ve)'),
)

STATUS_CHOICE = [
    ('stu', 'Student'),
    ('job', 'Job Holder'),
    ('unemployed', 'Unemployed')
]


DISTRICT_CHOICES = [
    ('Bagerhat', 'bagerhat'),
    ('Bandarban', 'bandarban'),
    ('Barguna', 'barguna'),
    ('Barisal', 'barisal'),
    ('Bhola', 'bhola'),
    ('Bogura', 'bogura'),
    ('Brahmanbaria', 'brahmanbaria'),
    ('Chandpur', 'chandpur'),
    ('Chapainawabganj', 'chapainawabganj'),
    ('Chattogram', 'chattogram'),
    ('Chuadanga', 'chuadanga'),
    ("Cox's Bazar", "cox's bazar"),
    ('Cumilla', 'cumilla'),
    ('Dhaka', 'dhaka'),
    ('Dinajpur', 'dinajpur'),
    ('Faridpur', 'faridpur'),
    ('Feni', 'feni'),
    ('Gaibandha', 'gaibandha'),
    ('Gazipur', 'gazipur'),
    ('Gopalganj', 'gopalganj'),
    ('Habiganj', 'habiganj'),
    ('Jamalpur', 'jamalpur'),
    ('Jessore', 'jessore'),
    ('Jhalokati', 'jhalokati'),
    ('Jhenaidah', 'jhenaidah'),
    ('Joypurhat', 'joypurhat'),
    ('Khagrachhari', 'khagrachhari'),
    ('Khulna', 'khulna'),
    ('Kishoreganj', 'kishoreganj'),
    ('Kurigram', 'kurigram'),
    ('Kushtia', 'kushtia'),
    ('Lakshmipur', 'lakshmipur'),
    ('Lalmonirhat', 'lalmonirhat'),
    ('Madaripur', 'madaripur'),
    ('Magura', 'magura'),
    ('Manikganj', 'manikganj'),
    ('Meherpur', 'meherpur'),
    ('Moulvibazar', 'moulvibazar'),
    ('Munshiganj', 'munshiganj'),
    ('Mymensingh', 'mymensingh'),
    ('Naogaon', 'naogaon'),
    ('Narail', 'narail'),
    ('Narayanganj', 'narayanganj'),
    ('Narsingdi', 'narsingdi'),
    ('Natore', 'natore'),
    ('Netrokona', 'netrokona'),
    ('Nilphamari', 'nilphamari'),
    ('Noakhali', 'noakhali'),
    ('Pabna', 'pabna'),
    ('Panchagarh', 'panchagarh'),
    ('Patuakhali', 'patuakhali'),
    ('Pirojpur', 'pirojpur'),
    ('Rajbari', 'rajbari'),
    ('Rajshahi', 'rajshahi'),
    ('Rangamati', 'rangamati'),
    ('Rangpur', 'rangpur'),
    ('Satkhira', 'satkhira'),
    ('Shariatpur', 'shariatpur'),
    ('Sherpur', 'sherpur'),
    ('Sirajganj', 'sirajganj'),
    ('Sunamganj', 'sunamganj'),
    ('Sylhet', 'sylhet'),
    ('Tangail', 'tangail'),
    ('Thakurgaon', 'thakurgaon'),
]

YEARS_CHOICE = [
    ('1st', 'First Year'),
    ('2nd', 'Second Year'),
    ('3rd', 'Third Year'),
    ('4th', 'Fourth Year'),
    ('ms', 'Masters')
]